### ISSUE TITLE
oauth.js error using 1.7.0

### ISSUE THREAD

**Issue by jamesyoung** [jpurcell/birdhouse#13]
Birdhouseapp using SDK 1.6.2 works great but breaks in 1.7.0. Below is the error :

[DEBUG] exception: url: lib/oauth.js, line: 304

[DEBUG] looking for breakpoint: lib/oauth.js, source: 192170792

[DEBUG] pause: url: lib/oauth.js, line: 304

[DEBUG] RESPONDING: 21_suspended_0*exception

[DEBUG] COMMAND: frames [1308879902058] => (

```
0
```

)

[DEBUG] fn = correctTimestampFromSrc, source = lib/oauth.js, lineNumber: 304

[DEBUG] fn = , source = lib/oauth.js, lineNumber: 549

**Comment by jpurcell** [comment]
Could this be related to issue #14?

**Comment by jamesyoung** [comment]
@jpurcell - yes, I believe so.
