### ISSUE TITLE
Authentication needed error

### ISSUE THREAD

**Issue by NexCon** [jpurcell/birdhouse#20]
I have gotten myself very confused over Twitter Oauth.  I am trying to post to Twitter from a mobile app. Is it correct that the only app specific details that I enter into your demo app is my consumer key and consumer secret? This is my error:
   [DEBUG] fn-api: accessor is {"consumerSecret":"hasMyCorrentSecretHere","tokenSecret":""}
   [INFO] var_dump: error (object):Error Domain=ASIHTTPRequestErrorDomain Code=3 "Authentication needed"          UserInfo=0x6c434b0 {NSLocalizedDescription=Authentication needed}
   [DEBUG] The API XHR request has failed! Status=4 and var_dump of e is undefined
Any ideas?

**Comment by jpurcell** [comment]
You will also need to set the callback url. Do you have a URL endpoint that is public somewhere?

**Comment by NexCon** [comment]
Oh my, I am so sorry! I actually did have the url in the var BH, but I had a typo in one of the other fields... caught it when I was trying to copy error messages. 
Thank you so much for your response... it spurred me to find my error!

**Comment by jpurcell** [comment]
There ya go! Glad to hear it's working! Cheers!
