### ISSUE TITLE
some bug in 0.9

### ISSUE THREAD

**Issue by lunika** [jpurcell/birdhouse#5]
A callback is missing in the XHR.error in the api function : 
// on error, show message
            XHR.onerror = function(e) {
                // access token and token secret are wrong
                if (e.error=="Unauthorized") {

```
            } else {
            }
            callback(false);
            return false;
        }
```

In twent function, in the callback of send_tweet nothing append if the callback return false. : 

btnTW.addEventListener('click',function() {
                send_tweet("status="+escape(tweet.value),function(retval){
                    if (retval===false) {
                        // execute the callback function
                        if (typeof(callback)=='function') {
                            callback(false);
                        }

```
                    winBG.close();
                    winTW.close();

                    return false;
                } else {
                    // hide the keyboard on Android because it doesn't automatically
                    if (Ti.Platform.osname=='android') {
                        Titanium.UI.Android.hideSoftKeyboard();
                    }

                    // execute the callback function
                    if (typeof(callback)=='function') {
                        callback(true);
                    }

                    winBG.close();
                    winTW.close();

                    return true;
                }
            });
```

I still have this problem : https://github.com/jpurcell/birdhouse/issues/4

I search but i found nothing...

**Comment by lunika** [comment]
in the debug version, error line 249 : 

it's "if" instead of "else if"

**Comment by jpurcell** [comment]
Hahaha, ok, so I had some committing issues. You are right, there was a syntax error and the callback function was missing. Those are fixed. I'll address your other issue on the issue #4 ticket.

Thank you for brining this to my attention!
